import React from 'react'
import Head from 'next/head'
import {PostCard, PostWidget, Categories} from '../../components'
import BlogStyle from '../../styles/Blog.module.scss'
import { getPosts } from '../../services'
import {FeaturedPosts} from '../../sections';
import { BlogHeader } from '../../components'
import { motion } from 'framer-motion'
// Fetch data at build time
export async function getStaticProps() {
    const posts = (await getPosts()) || [];
    return {
      props: {posts},
    };
  }

  const variants = {
    hidden:{opacity: 0, x:0, y:20},
    enter:{opacity:1, x:0, y:0},
    exit:{opacity:0,x:0,y:20}
  }

  export default function Home({ posts }) {

return (
  <motion.div initial="hidden" animate="enter" exit="exit" variants={variants} transition={{duration: 0.2, type: 'easeInOut'}}  >
    <BlogHeader/>
  <div className={BlogStyle.blogBody}>
        <div className='container mx-auto px-10 mb-8'>
        <Head>
        <title>Ariadne Maps Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="https://www.munich-startup.de/wp-content/uploads/2020/10/Ariadne-Maps-GmbH.jpeg" />
       </Head>
       <FeaturedPosts/>
       
    <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 scroll-smooth'>
    <div className="lg:col-span-8 col-span-1">
            {posts.map((post, index) => (
              <PostCard key={index} post={post.node} />
            ))}
          </div>
          <div className="lg:col-span-4 col-span-1">
            <div className="lg:sticky relative top-2">
              <PostWidget />
              <Categories />
            </div>
          </div>
        
        </div>  


        </div>
    </div>
  </motion.div>
    
  )
}



