import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


import {motion} from 'framer-motion'


import { useScroll } from '../components/useScroll'

import Brands from '../components/Brands'
import HomeBlogPosts from '../sections/HomeBlogPosts'

import CheckIcon from '@mui/icons-material/Check';
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';
import  VideoCarousel  from "../sections/VideoCarousel"



import Modal from 'react-modal';

import Carousel from 'react-multi-carousel';

import { useState } from 'react'

import styles from '../styles/Home.module.css'
import { Calendly, Testi2 } from '../components'



const variants = {
  hidden:{opacity: 0, x:0, y:0},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:0,y:0}
}
const Vvariants = {
  hidden:{opacity: 0, x:0, y:0},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:0,y:0}
}
const DUvariants= {
  hidden:{opacity: 0, x:0, y:200},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:1,x:0,y:0}

}
const LRvariants ={
  hidden:{opacity: 0, x:-200, y:0},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:-200,y:0}

}
const RLvariants ={
  hidden:{opacity: 0, x:200, y:0},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:200,y:0}

}






export default function Home() {
  const [element,controls] = useScroll();
 
  const [element2,controls2] = useScroll();
  const [element3,controls3] = useScroll();
  const [element4,controls4] = useScroll();
  const [element5,controls5] = useScroll();
  const [element6,controls6] = useScroll();
  const [element7,controls7] = useScroll();
  const [element8,controls8] = useScroll();
  const [element9,controls9] = useScroll();



  const customStyles = {
    overlay: {
      position: 'fixed',
      zIndex:1000,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255, 255, 255, 0.75)'
    },
    content: {
     
      overflow: 'auto',
      zIndex:300,
      top: '50%',
      left: '50%',
      right: 'auto',
      bottom: 'auto',
      marginRight: '-50%',
      height: '90vh',
      width: '100%',
      zIndex:'9999',
      transform: 'translate(-50%, -50%)',
    },
  };
  


  const responsive = {
  
    desktop: {
      breakpoint: { max: 4000, min: 768 },
      items: 1,
    },
    tablet: {
      breakpoint: { max: 768, min: 640 },
      items: 1,
    },
    mobile: {
      breakpoint: { max: 640, min: 0 },
      items: 1,
    },
  };
  

  const [modalIsOpen, setIsOpen] = useState(false);

  function openModal() {
    setIsOpen(true);
  }
  function closeModal() {
    setIsOpen(false);
  }

 
  return (
   <div >
      <div >
      <Head>
        <title>Ariadne Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.munich-startup.de/wp-content/uploads/2020/10/Ariadne-Maps-GmbH.jpeg" />
        <link
  rel="stylesheet"
  type="text/css"
  charSet="UTF-8"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>
        
       
      </Head>
        <div  className={styles.hero} >
          <div className={styles.heroContainer}>

            <div className = {styles.heroTextContainer}>
            <div className={styles.heroText}>
            <h1  >People Flow To Actionable Insights</h1>
              <p>Turn your existing customer traffic into an additional source of revenue</p>
              <Link href ="/company/contact"><a><button className=' bg-red-600 hover:bg-red-700 py-1 px-3 text-lg mt-5'>Let&rsquo;s Talk</button></a></Link>
            </div>
            </div>

            <div className={styles.heroScreen} >
            <video className={styles.bgVid} 
            poster = "/Photos/smallScreen.png"
            // initial="hidden" animate="enter" exit="exit" variants={Vvariants} transition={{duration: 2, type: 'easeInOut'}} 
            
            src ="/Videos/Hero2vid.mp4" type="videos/mp4" autoPlay playsInline muted loop  />
            <img src = "/Photos/smallScreen.png" />
            </div>

          </div>
        </div>

      <main className={styles.main}>
        <Brands/>
        
        <div className={styles.section1} id = "screens" ref = {element}
       

        >
         
          <motion.div
           transition={{duration: 0.4, type: 'easeInOut'}} 
           initial="hidden"  exit="exit"
           variants = {variants} animate = {controls}
          >
          <h1 className='text-center'>Unlock the value of your data and multiply your returns!</h1>
          </motion.div>
          
          <motion.div className={styles.section1screens}
          
           >
              <motion.div className={styles.screens}
              transition={{duration: 0.5, type: 'easeInOut'}} 
              initial="hidden"  exit="exit"
              variants = {LRvariants} animate = {controls}
              >
              <img 
            

              src = "/Photos/screens.png" />
              <div
               >
              <p
              
              className='text-center text-red-500 animate-bounce' ><button className=' hover:scale-105'  onClick={openModal} ><AddCircleOutlineIcon />&nbsp;Enlarge</button></p>
              </div>

              <Modal
        isOpen={modalIsOpen}
        preventScroll ={true}
        onRequestClose={closeModal}
        style={customStyles}
        contentLabel="Example Modal"
        shouldCloseOnEsc={
          true
        }
      >
        
        <div className='overscroll-contain ' >
        
        <div className='flex flex-row justify-end overscroll-contain' >
        <button className='rounded-full bg-red-500 px-3 text-white font-semibold'  onClick={closeModal}>close</button>
        </div>
        
        
        
          
          <div>
          <h1 className = "text-center text-4xl" >Omnichannel Solution</h1>
      <Carousel infinite 
      
      responsive={responsive}
      autoPlaySpeed={10000}
      itemClass="px-3"
      >
        <div className="flex flex-col items-center justify-center content-center align-center " >
            <div className='w-full' >
            <img src="/Photos/enlarge/eAnalytics.png"  />
            </div>
            <h1 className='text-3xl text-center' >Ariadne Analytics</h1>
            <p>People Counting, Dwell Time, Heat Map, Alerts, Transitions…</p>
          </div>

          <div className="flex flex-col items-center justify-center content-center align-center " >
            <div className='w-full' >
            <img src="/Photos/enlarge/eCRM.png" />
            </div>
            <h1 className='text-3xl text-center' >CRM Optin Tool</h1>
            <p>Customers opt-in and you can see the contact info store by store</p>
          </div>

          <div className="flex flex-col items-center justify-center content-center align-center " >
            <div className='w-full ' >
            <img src="/Photos/enlarge/ERP.png" />
            </div>
            <h1 className='text-3xl text-center' >ERP Data Integration</h1>
            <p>Measure the conversion rate of each product</p>
          </div>

          
          
      </Carousel>
    </div>

        
        
      </div>
      </Modal>
              </motion.div>
              <motion.div className={styles.intro}
              transition={{duration: 0.5, type: 'easeInOut'}} 
              initial="hidden"  exit="exit"
              variants = {RLvariants} animate = {controls}
              >
                <p>
                Ariadne is considered to be the Google Analytics of the physical world. Ariadne helps you to analyze your visitors&rsquo; behavior, it consults you on strategies, and provides you with recommendations for the future.
                </p>

                <p id={styles.list} className= 'leading-10'>

      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Footfall (Total and by area)<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Dwell Time(Total and by area)<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Heatmap (2D and 3D)<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Transitions between areas<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;ERP, BI, POS Integration

      </p>
              </motion.div>
          </motion.div>
        </div>

        <div className={styles.section2} ref = {element2}>
          
<motion.div
transition={{duration: 0.4, type: 'easeInOut'}} 
initial="hidden"  exit="exit"
variants = {variants} animate = {controls2}>
<h1 className='text-center'>See how our customers are succeeding with Ariadne</h1>
</motion.div>
          <motion.div
           transition={{duration: 0.5, type: 'easeInOut'}} 
           initial="hidden"  exit="exit"
           variants = {variants} animate = {controls2}

          
          >
          <VideoCarousel/>
          </motion.div>
        </div>
        <div className={styles.section3} >
              <motion.div
              transition={{duration: 0.4, type: 'easeInOut'}} 
              initial="hidden"  exit="exit"
              variants = {variants} animate = {controls3}>
          <h1 className='text-center'>The Ariadne Platform</h1>

              </motion.div>

          <div className={`${styles.gifbox}`} ref = {element3}>
            <motion.div className = {styles.giftext}
             transition={{duration: 0.5, type: 'easeInOut'}} 
             initial="hidden"  exit="exit"
             variants = {LRvariants} animate = {controls3}>
              <h3>Ariadne Analytics</h3>
              <p>Obtain people counting, heatmaps, loyalty rate and more!</p>
              <p>With Ariadne analytics, you can review your performance in real time.</p>
            </motion.div>

            <motion.div className = {styles.gif}
             transition={{duration: 0.5, type: 'easeInOut'}} 
             initial="hidden"  exit="exit"
             variants = {RLvariants} animate = {controls3}
            >
            <video   playsInline className='pointer-events-none' width="100%" src="/Videos/h1.mp4" autoPlay loop muted type = "videos/mp4"/>
            </motion.div>

          </div>

          <div className={styles.gifbox} ref = {element4}>
            <motion.div className = {styles.giftext}
            transition={{duration: 0.5, type: 'easeInOut'}} 
            initial="hidden"  exit="exit"
            variants = {LRvariants} animate = {controls4}
            
            >
              <h3>Ariadne Navigation</h3>
              <p>Navigate your visitors and guests for an enhanced experience!</p>
              <p>Present promotions in your map to engage and enhance your visitors satisfaction.</p>
            </motion.div>
            <motion.div className = {styles.gif}
            transition={{duration: 0.5, type: 'easeInOut'}} 
            initial="hidden"  exit="exit"
            variants = {RLvariants} animate = {controls4}
            
            >
            <video   playsInline className='pointer-events-none' width="100%" src="/Videos/h2.mp4" autoPlay loop muted type = "videos/mp4"/>
            </motion.div>
          </div>

          <div className={styles.gifbox} ref = {element5}>
            <motion.div className = {styles.giftext}
            transition={{duration: 0.5, type: 'easeInOut'}} 
            initial="hidden"  exit="exit"
            variants = {LRvariants} animate = {controls5}
            >
              <h3>Ariadne Engagement</h3>
              <p>Ariadne enables your visitors to opt-in to your loyalty program!</p>
              <p>The opt-in feature enables you to push notifications to your visitors the right moment.</p>
            </motion.div>
            <motion.div className = {styles.gif}
             transition={{duration: 0.5, type: 'easeInOut'}} 
             initial="hidden"  exit="exit"
             variants = {RLvariants} animate = {controls5}
            >
            <video   playsInline className='pointer-events-none' width="100%" src="/Videos/h3.mp4" autoPlay loop muted type = "videos/mp4"/>
            </motion.div>
          </div>

          <div className={styles.gifbox} ref = {element6}>
            <motion.div className = {styles.giftext}
            transition={{duration: 0.5, type: 'easeInOut'}} 
            initial="hidden"  exit="exit"
            variants = {LRvariants} animate = {controls6}
            
            >
              <h3>Ariadne Mapping</h3>
              <p>Transform your physical business into a digital landscape!</p>
              <p>Ariadne boosts your efficiency by enabling you to map and localize your products.</p>
            </motion.div>
            <motion.div className = {styles.gif}
            transition={{duration: 0.5, type: 'easeInOut'}} 
            initial="hidden"  exit="exit"
            variants = {RLvariants} animate = {controls6}
            >
            <video   playsInline className='pointer-events-none' width="100%" src="/Videos/h4.mp4" autoPlay loop muted type = "videos/mp4"/>
            </motion.div>
          </div>
          

        </div>

        <div className={styles.section4} ref={element7}>
          <motion.div
          transition={{duration: 0.4, type: 'easeInOut'}} 
          initial="hidden"  exit="exit"
          variants = {variants} animate = {controls7}
          >
        <h1 className='text-center'>Trusted by industry leaders</h1>

          </motion.div>

        <motion.div
        transition={{duration: 0.5, type: 'easeInOut'}} 
        initial="hidden"  exit="exit"
        variants = {variants} animate = {controls7}

        
        >
        <Testi2/>
        </motion.div>

        </div>
        
        <div className={styles.section6} ref ={element8}>
          <motion.div
          
          transition={{duration: 0.4, type: 'easeInOut'}} 
initial="hidden"  exit="exit"
variants = {variants} animate = {controls8}>
          <h1 className="text-center">Spotlight</h1>


          </motion.div>
          <motion.div className={styles.blogCarousel}
          transition={{duration: 0.5, type: 'easeInOut'}} 
          initial="hidden"  exit="exit"
          variants = {variants} animate = {controls8}
  
          
          >
          <HomeBlogPosts/>

          </motion.div>
        </div>
        
        <div className={styles.section5} ref = {element9} >
        <motion.div
           transition={{duration: 0.5, type: 'easeInOut'}} 
           initial="hidden"  exit="exit"
           variants = {DUvariants} animate = {controls9}
        >
        <h1 className='text-center'>Get Started</h1>
        <p className='text-center'>Ariadne solution can be deployed on the premises just by plugging the devices in 
and  requires no additional infrastructure.</p>
        </motion.div>
          <div className={styles.products}>

          <motion.div className = {styles.product}
          transition={{duration: 0.5, type: 'easeInOut'}} 
          initial="hidden"  exit="exit"
          variants = {DUvariants} animate = {controls9}
          
          >
          <div className={styles.productImg}>
          <Image src="/Photos/floor.png" height={260} width={350}/>

            </div>
          
                  <h4 className='my-3'>Configuration</h4>
                  <p>Let our team design a project based on your floor plan and industry.</p>
          </motion.div>

          <motion.div className = {styles.product}
          transition={{duration: 0.6, type: 'easeInOut'}} 
          initial="hidden"  exit="exit"
          variants = {DUvariants} animate = {controls9}>
            <div className={styles.productImg}>
          <Image src="/Photos/device2.png" height={260} width={350} />

            </div>
                  <h4 className='my-3'>Installation</h4>
                  <p>Simply plug the devices in the predetermined sockets.</p>
          </motion.div>

          <motion.div className = {styles.product}
          transition={{duration: 0.9, type: 'easeInOut'}} 
          initial="hidden"  exit="exit"
          variants = {DUvariants} animate = {controls9}
          >
          <div className={styles.productImg}>
          <Image src="/Photos/screen.png" height={260} width={350}/>

            </div>
          
                  <h4 className='my-3'>The Dashboard</h4>
                  <p>Voila! Now you can make the most out of your existing traffic.</p>
          </motion.div>


          </div>


        </div>

        

        <div className={styles.section7}>
          <h1 className="text-center">Let&rsquo; talk</h1>
          

      <Calendly/>
          
        </div>

      </main>
      
    </div>
   </div>
  )
}
