import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Script from 'next/script'

import {motion} from 'framer-motion'




import Brands from '../components/Brands'
import HomeBlogPosts from '../sections/HomeBlogPosts'

import CheckIcon from '@mui/icons-material/Check';
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';
import  VideoCarousel  from "../sections/VideoCarousel"
import Testimonials from '../components/Testimonials'


import Modal from 'react-modal';

import Carousel from 'react-multi-carousel';

import { useState } from 'react'

import styles from '../styles/Home.module.css'
import { Testi2 } from '../components'




// Modal.setAppElement('#screens');

const variants = {
  hidden:{opacity: 0, x:0, y:20},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:0,y:20}
}
const herovariants = {
  hidden:{opacity: 0, x:-200, y:0},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:0,y:-200}

}
const heroVvariants = {
  hidden:{opacity: 0, x:0, y:-200},
  enter:{opacity:1, x:0, y:0},
  exit:{opacity:0,x:0,y:-200}

}





export default function Home() {
 



  const customStyles = {
    overlay: {
      position: 'fixed',
      zIndex:1000,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255, 255, 255, 0.75)'
    },
    content: {
     
      overflow: 'auto',
      zIndex:300,
      top: '50%',
      left: '50%',
      right: 'auto',
      bottom: 'auto',
      marginRight: '-50%',
      height: '90vh',
      width: '100%',
      zIndex:'9999',
      transform: 'translate(-50%, -50%)',
    },
  };
  


  const responsive = {
  
    desktop: {
      breakpoint: { max: 4000, min: 768 },
      items: 1,
    },
    tablet: {
      breakpoint: { max: 768, min: 640 },
      items: 1,
    },
    mobile: {
      breakpoint: { max: 640, min: 0 },
      items: 1,
    },
  };
  

  const [modalIsOpen, setIsOpen] = useState(false);

  function openModal() {
    setIsOpen(true);
  }
  function closeModal() {
    setIsOpen(false);
  }

 
  return (
   <div >
      <motion.div initial="hidden" animate="enter" exit="exit" variants={variants} transition={{duration: 0.2, type: 'easeInOut'}}  >
      <Head>
        <title>Ariadne Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.munich-startup.de/wp-content/uploads/2020/10/Ariadne-Maps-GmbH.jpeg" />
        <link
  rel="stylesheet"
  type="text/css"
  charset="UTF-8"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>
        
       
      </Head>
        <motion.div exit={{opacity:0}}  className={styles.hero} >
          <div className={styles.heroContainer}>

            <div className = {styles.heroTextContainer}>
            <div className={styles.heroText}>
            <motion.h1 initial="hidden" animate="enter" exit="exit" variants={herovariants} transition={{duration: 0.5, type: 'spring', bounce: 0.3}} >People Flow To Actionable Insights</motion.h1>
              <motion.p initial="hidden" animate="enter" exit="exit" variants={herovariants} transition={{duration: 0.2, type: 'easeInOut'}}>Turn your existing customer traffic into an additional source of revenue</motion.p>
              <Link href ="/company/contact"><a><button className='animate-pulse bg-red-600 hover:bg-red-700 py-1 px-3 text-lg mt-5'>Lets Talk</button></a></Link>
            </div>
            </div>

            <div className={styles.heroScreen} >
            <motion.video className='pointer-events-none' initial="hidden" animate="enter" exit="exit" variants={heroVvariants} transition={{duration: 0.5, type: 'spring', bounce: 0.3 }}
            src ="/Videos/Hero2vid.mp4" type="videos/mp4" autoPlay playsInline muted loop  />
            <img src = "/Photos/smallScreen.png" />
            </div>

          </div>
        </motion.div>

      <main className={styles.main}>
        <Brands/>
        <div className={styles.section1} id = "screens">
         
          <h1 className='text-center'>Unlock the value of your data and multiply your returns!</h1>
          <div className={styles.section1screens}>
              <div className={styles.screens}>
              <img src = "/Photos/screens.png" />
              <p className='text-center text-red-500 animate-bounce' ><button className=' hover:scale-105'  onClick={openModal} ><AddCircleOutlineIcon />&nbsp;Enlarge</button></p>

              <Modal
        isOpen={modalIsOpen}
        preventScroll ={true}
        onRequestClose={closeModal}
        style={customStyles}
        contentLabel="Example Modal"
        shouldCloseOnEsc={
          true
        }
      >
        
        <div className='overscroll-contain ' >
        
        <div className='flex flex-row justify-end overscroll-contain' >
        <button className='rounded-full bg-red-500 px-3 text-white font-semibold'  onClick={closeModal}>close</button>
        </div>
        
        
        
          
          <div>
          <h1 className = "text-center text-4xl" >Omnichannel Solution</h1>
      <Carousel infinite 
      
      responsive={responsive}
      autoPlaySpeed={10000}
      itemClass="px-3"
      >
        <div className="flex flex-col items-center justify-center content-center align-center " >
            <div className='w-full' >
            <img src="/Photos/enlarge/eAnalytics.png"  />
            </div>
            <h1 className='text-3xl text-center' >Ariadne Analytics</h1>
            <p>People Counting, Dwell Time, Heat Map, Alerts, Transitions…</p>
          </div>

          <div className="flex flex-col items-center justify-center content-center align-center " >
            <div className='w-full' >
            <img src="/Photos/enlarge/eCRM.png" />
            </div>
            <h1 className='text-3xl text-center' >CRM Optin Tool</h1>
            <p>Customers opt-in and you can see the contact info store by store</p>
          </div>

          <div className="flex flex-col items-center justify-center content-center align-center " >
            <div className='w-full ' >
            <img src="/Photos/enlarge/ERP.png" />
            </div>
            <h1 className='text-3xl text-center' >ERP Data Integration</h1>
            <p>Measure the conversion rate of each product</p>
          </div>

          
          
      </Carousel>
    </div>

        
        
      </div>
      </Modal>
              </div>
              <div className={styles.intro}>
                <p>
                Ariadne is considered to be the Google Analytics of the physical world. Ariadne helps you to analyze your visitors&rsquo; behavior, it consults you on strategies, and provides you with recommendations for the future.
                </p>

                <p id={styles.list} className= 'leading-10'>

      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Footfall (Total and by area)<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Dwell Time(Total and by area)<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Heatmap (2D and 3D)<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;Transitions between areas<br/>
      <span><CheckIcon /></span>&nbsp; &nbsp; &nbsp;ERP, BI, POS Integration

      </p>
              </div>
          </div>
        </div>

        <div className={styles.section2}>
          <h1 className='text-center'>See how our customers are succeeding with Ariadne</h1>

          <VideoCarousel/>
        </div>
        <div className={styles.section3}>

          <h1 className='text-center'>The Ariadne Platform</h1>

          <div className={`${styles.gifbox}`} >
            <div className = {styles.giftext}>
              <h3>Ariadne Analytics</h3>
              <p>Obtain people counting, heatmaps, loyalty rate and more!</p>
              <p>With Ariadne analytics, you can review your performance in real time.</p>
            </div>
            <div className = {styles.gif}>
            <video webkit-playsInline playsInline className='pointer-events-none' width="100%" src="/Videos/h1.mp4" autoPlay loop muted type = "videos/mp4"/>
            </div>
          </div>

          <div className={styles.gifbox} >
            <div className = {styles.giftext}>
              <h3>Ariadne Analytics</h3>
              <p>Obtain people counting, heatmaps, loyalty rate and more!</p>
              <p>With Ariadne analytics, you can review your performance in real time.</p>
            </div>
            <div className = {styles.gif}>
            <video webkit-playsInline playsInline className='pointer-events-none' width="100%" src="/Videos/h2.mp4" autoPlay loop muted type = "videos/mp4"/>
            </div>
          </div>

          <div className={styles.gifbox} >
            <div className = {styles.giftext}>
              <h3>Ariadne Analytics</h3>
              <p>Obtain people counting, heatmaps, loyalty rate and more!</p>
              <p>With Ariadne analytics, you can review your performance in real time.</p>
            </div>
            <div className = {styles.gif}>
            <video webkit-playsInline playsInline className='pointer-events-none' width="100%" src="/Videos/h3.mp4" autoPlay loop muted type = "videos/mp4"/>
            </div>
          </div>

          <div className={styles.gifbox} >
            <div className = {styles.giftext}>
              <h3>Ariadne Analytics</h3>
              <p>Obtain people counting, heatmaps, loyalty rate and more!</p>
              <p>With Ariadne analytics, you can review your performance in real time.</p>
            </div>
            <div className = {styles.gif}>
            <video webkit-playsInline playsInline className='pointer-events-none' width="100%" src="/Videos/h4.mp4" autoPlay loop muted type = "videos/mp4"/>
            </div>
          </div>
          

        </div>

        <div className={styles.section4}>
        <h1 className='text-center'>Trusted by industry leaders</h1>

        <Testi2/>

        </div>
        
        <div className={styles.section6}>
          <h1 className="text-center">Spotlight</h1>
          <div className={styles.blogCarousel} >
          <HomeBlogPosts/>

          </div>
        </div>
        
        <div className={styles.section5}>
        <h1 className='text-center'>Get Started</h1>
        <p className='text-center'>Ariadne solution can be deployed on the premises just by plugging the devices in 
and  requires no additional infrastructure.</p>
          <div className={styles.products}>

          <div className = {styles.product}>
          <div className={styles.productImg}>
          <Image src="/Photos/floor.png" height={260} width={350}/>

            </div>
          
                  <h4 className='my-3'>Configuration</h4>
                  <p>Let our team design a project based on your floor plan and industry.</p>
          </div>

          <div className = {styles.product}>
            <div className={styles.productImg}>
          <Image src="/Photos/device2.png" height={260} width={350} />

            </div>
                  <h4 className='my-3'>Installation</h4>
                  <p>Simply plug the devices in the predetermined sockets.</p>
          </div>

          <div className = {styles.product}>
          <div className={styles.productImg}>
          <Image src="/Photos/screen.png" height={260} width={350}/>

            </div>
          
                  <h4 className='my-3'>The Dashboard</h4>
                  <p>Voila! Now you can make the most out of your existing traffic.</p>
          </div>


          </div>


        </div>

        

        <div className={styles.section7}>
          <h1 className="text-center">Let&rsquo; talk</h1>
          

      <Script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" />

          <div className="calendly-inline-widget" id ={styles.calendly} data-url="https://calendly.com/georgios-ariadnemaps/30min"  ></div>
          
        </div>

      </main>
      
    </motion.div>
   </div>
  )
}
